### ISSUE TITLE
Make it so that the actual data washing must be enabled from config.php only

### ISSUE THREAD

**Issue by mudrd8mz** [brendanheywood/moodle-local_datacleaner#5]
I was thinking about the risks and you are right in the description that they are quite scary. It is just too easy to loose the context and perform the fatal operations on the live site in these situations. Good to see checking mechanisms in place to prevent accidental execution on the production site. 

What about adding yet another one - the actual data washing would be executed only if a special flag was enabled via config.php. And it must be physically in config.php only, not in the database. Something like
```
if (empty($CFG->config_php_settings['local_datacleaner_allowexecution'])) {
    cli_error('Execution not allowed here');
}
```

**Comment by brendanheywood** [comment]
I really like this, we will be doing this (a bit swamped right now...)
