### ISSUE TITLE
Concatenate operator not supported by AMOS yet

### ISSUE THREAD

**Issue by mudrd8mz** [brendanheywood/moodle-local_datacleaner#7]
FYI, the AMOS parser at lang.moodle.org does not support the concatenation operator as used in 
you lang file (e.g. line 33 and others). As a consequence, your plugin's strings can not be registered with AMOS at the moment. Sorry for that annoyance. Meantime, we generally recommend to avoid using the operator in the string files and simply put all the strings into one long string (line lenght auto-checks are excluded for lang files).

**Comment by brendanheywood** [comment]
Fixed
